### ISSUE TITLE
Filter screen in Remote Syslog Classic not keeps previous position

### ISSUE THREAD

**Issue by HarmVeenstra** [tslenter/RSX-RSC#37] opened 2021-03-05 19:24 UTC
When filtering, it filters the log and when you press filter again (To change/remove filter)... You have to scroll up/down to find the filter box, it retains it's original position but the log screen keeps scrolling down with new events (Or when scrolling up) . Screen turns gey indicating the filter box is shown, but it doesn't snap to the current screenposition

**Comment by tslenter** [comment] 2021-03-07 16:00
Hi Harm,

We did a quick update for the file: PHPTail.php within the development code. (We need to do some additional testing). When using the filter option it automatically scrolls to the top and places the windows below the navigation bar. The window can now be moved around as well.

To make a quick update:
mkdir ~/rsc_update
cd ~/rsc_update
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/development/rsc/PHPTail.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php

Rollback:
mkdir ~/rsc_rollback
cd ~/rsc_rollback
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/master/rsc/PHPTail.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php

**Comment by HarmVeenstra** [comment] 2021-03-07 16:50
When I'm at the end, last entries, of the log and press Filter the screen turns grey, I'm at the top (oldest entry) again and the searchbox is at the bottom. I would expect the filter box to always appear in the position of the screen, not top or bottom. Perhap a filter box in the top bar would be better then a floating one?

**Comment by HarmVeenstra** [comment] 2021-03-08 10:08
If I press filter now, updated php file again first, I don't see it. But if I press Filter, the box appears and disappears when I release my left button. When I press Filter and hold my left button and place my mouse cursor on the filter box, it stays and I can filter words..

**Comment by tslenter** [comment] 2021-03-08 11:24
Hi Harm,

We were able to duplicate the issue " expect the filter box to always appear in the position of the screen,".  When the filter window is moved the filter window appears @ the bottom. For now, we disabled this option.  So the filter window will always appear @ the top as default. When closing or setting a filter we scroll down to the newest messages. We may integrate the search function in the navigation bar in the future. For now, we cannot duplicate the issue of the "disappeared filter window". We run tests for Windows 10 - Chrome - Edge or Firefox. Which configuration do you have? 

To make a quick update:
mkdir ~/rsc_update
cd ~/rsc_update
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/development/rsc/PHPTail.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php

Rollback:
mkdir ~/rsc_rollback
cd ~/rsc_rollback
wget https://raw.githubusercontent.com/tslenter/RSX-RSC/master/rsc/PHPTail.php
sudo cp ./PHPTail.php /var/www/html/rsc/PHPTail.php

**Comment by HarmVeenstra** [comment] 2021-03-08 11:59
My configuration is Windows 10 and Edge Chromiuim, tested it in Chrom just now and same issue. I'm at the bottom of the log, press Filter. screen turns grey and the filter box is somewhere in the 8000 lines of logging. My log is at oldest entry at that moment when I press Filter.  (Top of list and not at bottom (newest) entry)

**Comment by HarmVeenstra** [comment] 2021-03-08 12:01
When I press and hold the filter button, the filter box does appear not matter where you are in the log window

**Comment by tslenter** [comment] 2021-03-08 16:05
The configuration as you described should work. We made a video of how it works with the latest update: Video can be found @ https://www.youtube.com/watch?v=QG1OfEp5I2w . The test is done with a live stream of logging and 91000+ lines of logging.  Maybe we did test the wrong way.  So what to expect: 

Click "filter" --> screen scrolls up and opens filter window
Click "done or exit" in the filter window --> screen scrolls down to the newest logging

We cannot duplicate your issue. Maybe you do something different than we did within our tests.

**Comment by HarmVeenstra** [comment] 2021-03-08 17:28
it keeps a certain position a few screens loweer and doesn't pop-up on top
like your video... Perhaps I can share my screen with you using teamviewer
and I can show you what I mean?

**Comment by tslenter** [comment] 2021-03-09 08:43
I think it is clear what you mean. We will try some other configurations to see if we get the same issue. We actually need to duplicate the issue to troubleshoot it. We use Teamviewer if all configuration and logging pass the test and the issue is still not duplicated.

**Comment by HarmVeenstra** [comment] 2021-03-11 08:58
Problem is fixed, seems like my apache2 was doing something weird and restarted the proces. If I now click on filter, anywhere in the log, it scrolls up and shows me the filter box.  Perfect!

**Comment by tslenter** [comment] 2021-03-11 11:30
Good to know that the issue is resolved by restarting the apache2 service. Thanks for sharing. We will close this issue and update the master branch.

**Closed as completed by tslenter** 2021-03-11 11:30 UTC
